name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # https://nodejs.org/en/about/releases/
        #Â https://pnpm.io/installation#compatibility
        version:
          - node: 18
          - node: 20

    name: Node.js ${{ matrix.version.node }}
    env:
      NODE_VERSION: ${{ matrix.version.node }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            node_modules/.cache/turbo
            node_modules/.pnpm
          key: ${{ runner.os }}-node${{ matrix.version.node }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version.node }}

      - run: corepack enable && pnpm --version

      - run: pnpm install --recursive --loglevel=error

      - run: pnpm build --filter='!@edge-runtime/docs'

      - run: pnpm run test --filter='!@edge-runtime/docs'

      - name: Generate coverage
        run: pnpm coverage
